import coverage from './coverage.json'

// The area CHIRAAG can actually route within.
//
// coverage.json is regenerated by pipeline/run_ingestion.py on every scoring
// run, from the same street network that run just wrote. Ingest a new ward and
// the outline grows to include it without anyone remembering to update it.
// Don't hand-edit the JSON.
//
// Note this is not the ingestion radius. The clip radius says where data was
// cut; this says where a requested point can still snap onto a street, which
// is the only thing a user cares about. Those are not the same shape, and
// drawing the former would promise coverage that does not exist.

export const COVERAGE_AREA_KM2 = coverage.area_km2
export const COVERAGE_GENERATED_AT = coverage.generated_at

// One ring per connected area, so a second, distant ward draws as its own
// island rather than being swallowed by a hull stretched across the gap.
const RINGS = coverage.rings

export const COVERAGE_BOUNDARY = {
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'MultiPolygon',
    coordinates: RINGS.map(ring => [ring]),
  },
}

// The whole world with every surveyed area punched out of it, so everywhere
// we have not surveyed can be dimmed. The same argument the street-level
// hatching makes -- here is what we know and what we don't -- drawn at city
// scale. Holes wind opposite to the exterior, hence the reverse.
export const COVERAGE_MASK = {
  type: 'Feature',
  properties: {},
  geometry: {
    type: 'Polygon',
    coordinates: [
      [[-180, -85], [180, -85], [180, 85], [-180, 85], [-180, -85]],
      ...RINGS.map(ring => ring.slice().reverse()),
    ],
  },
}
