"""
pipeline/run_ingestion.py

One-off orchestrator that runs the full CHIRAAG data pipeline end-to-end:

  1. Pull street geometry from OpenStreetMap        -> road_segments
  2. Pull streetlight points from Mapillary          -> streetlights
  3. Snap each streetlight onto its nearest road
  4. Compute dark_fraction / longest_gap_m per road segment
  5. Write those scores back to road_segments

This is an OFFLINE batch job. The live API (app/) never imports or calls
this file -- it only reads whatever is already sitting in road_segments /
streetlights. Run this manually.
Usage:
    python -m pipeline.run_ingestion \\
        --place "Connaught Place, New Delhi, India" \\
        --bbox "77.20,28.60,77.24,28.64" \\
        --mapillary-token YOUR_TOKEN

    # Re-score existing roads/lights without re-fetching from OSM/Mapillary:
    python -m pipeline.run_ingestion --skip-osm --skip-lights \\
        --bbox "" --mapillary-token ""
"""

import argparse
import json
import os
import sys
from datetime import datetime, timezone

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import geopandas as gpd
from sqlalchemy import create_engine, text
import pandas as pd
from shapely.geometry.polygon import orient
from shapely.ops import unary_union

from app.config import settings
from app.db import Base
import app.models
from pipeline.ingest_osmnx import ingest_osm
from pipeline.ingest_mapillary import ingest_mapillary
from pipeline.snap_to_road import snap_lights_to_roads
from pipeline.gap_analysis import calculate_segment_metrics
from pipeline.ingest_imagery import (
    IMAGED_DARK_FRACTION,
    MIN_IMAGES_FOR_DARK,
)


# ---------------------------------------------------------------------------
# Coverage boundary
#
# The map dims everywhere outside the surveyed area, so the front end needs to
# know its shape. Computing it here rather than serving it from an endpoint
# means it is derived at the same moment the data it describes is written --
# it cannot drift out of step, and costs nothing at request time on a 0.1 CPU
# host. Ingest a new ward and the boundary grows to include it automatically.
# ---------------------------------------------------------------------------

# Must match max_snap_m in services/routing.find_optimal_route: the boundary
# marks where a requested point can still snap onto a street, which is exactly
# where routing works.
COVERAGE_SNAP_RADIUS_M = 250.0

# Tolerance for thinning the outline. 40 m keeps it to a few dozen points and
# within a fraction of a percent of the true area.
COVERAGE_SIMPLIFY_M = 40.0

COVERAGE_OUTPUT = os.path.normpath(os.path.join(
    os.path.dirname(__file__), "..", "..",
    "chiraag_frontend", "src", "lib", "coverage.json",
))


def export_coverage_boundary(roads_gdf: gpd.GeoDataFrame, path=COVERAGE_OUTPUT):
    """
    Write the outline of the routable area for the front end to draw.

    Every street buffered by the snap radius, unioned, simplified. Disconnected
    areas are kept as separate rings rather than collapsed to the largest --
    ingesting a second, distant ward must show up as a second island, not
    silently vanish.
    """
    if roads_gdf.empty:
        print("No road segments -- skipping coverage boundary export.")
        return

    if not os.path.isdir(os.path.dirname(path)):
        # Expected on a backend-only deployment; the file lives in the front
        # end's source tree and is committed, so there is nothing to update.
        print(f"No front end at {os.path.dirname(path)} -- skipping coverage export.")
        return

    projected = roads_gdf.to_crs(epsg=32643)
    blob = unary_union(projected.geometry.buffer(COVERAGE_SNAP_RADIUS_M))

    pieces = list(blob.geoms) if blob.geom_type == "MultiPolygon" else [blob]

    rings, area_m2 = [], 0.0
    for piece in sorted(pieces, key=lambda g: g.area, reverse=True):
        simplified = piece.simplify(COVERAGE_SIMPLIFY_M)

        if simplified.is_empty or not simplified.is_valid:
            continue

        area_m2 += simplified.area

        # Counterclockwise, so the front end can reverse it for the mask hole.
        lonlat = gpd.GeoSeries([simplified], crs=32643).to_crs(4326).iloc[0]
        lonlat = orient(lonlat, sign=1.0)

        rings.append([[round(x, 5), round(y, 5)] for x, y in lonlat.exterior.coords])

    if not rings:
        print("Coverage boundary came out empty -- leaving the existing file alone.")
        return

    payload = {
        "_comment": (
            "Generated by pipeline/run_ingestion.py. Do not edit by hand -- "
            "re-run the ingestion instead."
        ),
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "segments": int(len(roads_gdf)),
        "snap_radius_m": COVERAGE_SNAP_RADIUS_M,
        "area_km2": round(area_m2 / 1e6, 2),
        "rings": rings,
    }

    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")

    shape = f"{len(rings)} areas" if len(rings) > 1 else "1 area"
    print(f"Coverage boundary written: {shape}, "
          f"{sum(len(r) - 1 for r in rings)} points, "
          f"{payload['area_km2']} km2 -> {path}")


def load_image_counts(engine) -> dict:
    """
    {road_id: image_count}, empty until pipeline.ingest_imagery has run.

    That module adds the column on first use, so its absence simply means
    imagery coverage has not been measured yet -- in which case scoring falls
    back to treating every lampless street as unobserved, exactly as before.
    """
    try:
        with engine.connect() as conn:
            rows = conn.execute(
                text(
                    "SELECT id, image_count FROM road_segments "
                    "WHERE image_count IS NOT NULL"
                )
            ).fetchall()
    except Exception:
        return {}

    return {row[0]: int(row[1] or 0) for row in rows}


def load_roads(engine) -> gpd.GeoDataFrame:
  
    return gpd.read_postgis(
        "SELECT id, length_m, geom AS geometry FROM road_segments",
        engine,
        geom_col="geometry",
    )


def load_lights(engine) -> gpd.GeoDataFrame:
    return gpd.read_postgis(
        "SELECT id, geom AS geometry FROM streetlights",
        engine,
        geom_col="geometry",
    )


def score_and_write_segments(engine, roads_gdf: gpd.GeoDataFrame, lights_gdf: gpd.GeoDataFrame):
    

    if roads_gdf.empty:
        print("No road segments found -- nothing to score. Run OSM ingestion first.")
        return

    if lights_gdf.empty:
        print("No streetlights found -- leaving all segments unscored (fully dark by default).")
        snapped = {}
    else:
        snapped = snap_lights_to_roads(roads_gdf, lights_gdf)

    image_counts = load_image_counts(engine)

    if image_counts:
        print(f"Imagery coverage known for {len(image_counts)} segments.")

    updates = []
    for _, road in roads_gdf.iterrows():
        road_id = road["id"]
        raw_length = road["length_m"]
        segment_length = float(raw_length) if pd.notna(raw_length) else 0.0
        light_positions = snapped.get(road_id, [])

        if light_positions:
            metrics = calculate_segment_metrics(
                segment_length,
                light_positions
            )

            updates.append({
                "id": road_id,
                "dark_fraction": metrics["dark_fraction"],
                "longest_gap_m": metrics["longest_gap_m"],
                "observation_state": "predicted",
            })

        else:
            # No lamp near this street -- but two very different situations
            # hide behind that, and only one of them is genuine ignorance.
            n_images = image_counts.get(road_id, 0)

            if n_images >= MIN_IMAGES_FOR_DARK:
                # Cameras have been down this street repeatedly and no street
                # light was detected anywhere along it. That is evidence of
                # darkness, not an absence of evidence, and scoring it as
                # unobserved throws it away.
                #
                # longest_gap_m stays NULL: we can say the street looks unlit,
                # not where along it the gaps fall.
                updates.append({
                    "id": road_id,
                    "dark_fraction": IMAGED_DARK_FRACTION,
                    "longest_gap_m": None,
                    "observation_state": "imaged_dark",
                })

            else:
                # Nobody has been down here with a camera, or not often enough
                # to speak for the whole street. Say so, and let the router
                # treat it as carrying no information.
                updates.append({
                    "id": road_id,
                    "dark_fraction": None,
                    "longest_gap_m": None,
                    "observation_state": "unobserved",
                })


    with engine.connect() as conn:
        audited_count = conn.execute(
            text(
                "SELECT count(*) FROM road_segments "
                "WHERE observation_state = 'audited'"
            )
        ).scalar() or 0

    print(f"Writing scores for {len(updates)} road segments...")

    if audited_count:
        print(
            f"Preserving {audited_count} human-audited segments "
            "(inferred scores will not overwrite them)."
        )

    with engine.begin() as conn:
        # Human ground truth outranks inference.
        #
        # Without the second clause this statement overwrites every audited
        # segment with a Mapillary-derived score, silently discarding work
        # somebody did by walking the street after dark. The night_audits rows
        # survive, but nothing reads them again, so the evidence is lost in
        # practice -- and every re-score of the pipeline destroys it afresh.
        #
        # IS DISTINCT FROM rather than <> so that a NULL observation_state --
        # a segment ingested but never scored -- is still updated.
        conn.execute(
            text("""
                UPDATE road_segments
                SET dark_fraction = :dark_fraction,
                    longest_gap_m = :longest_gap_m,
                    observation_state = :observation_state
                WHERE id = :id
                  AND observation_state IS DISTINCT FROM 'audited'
            """),
            updates,
        )

    print("Done scoring segments.")


def main():
    parser = argparse.ArgumentParser(description="Run the CHIRAAG ingestion pipeline.")
    parser.add_argument("--place", default="Connaught Place, New Delhi, India",
                         help="Place name passed to OSMnx for street geometry. "
                              "Only works for places that resolve to a (Multi)Polygon "
                              "boundary -- landmarks/POIs will fail. Prefer --lat/--lon "
                              "for those instead.")
    parser.add_argument("--lat", type=float, default=None,
                         help="Center latitude for point-based OSM ingestion "
                              "(bypasses place-name geocoding entirely).")
    parser.add_argument("--lon", type=float, default=None,
                         help="Center longitude for point-based OSM ingestion.")
    parser.add_argument("--radius", type=float, default=1000,
                         help="Radius in meters around --lat/--lon to pull streets from. "
                              "Only used when --lat/--lon are given. Default: 1000.")
    parser.add_argument("--bbox", default="",
                         help="Mapillary bounding box as 'minLon,minLat,maxLon,maxLat'. "
                              "Required unless --skip-lights is set.")
    parser.add_argument("--mapillary-token", default="",
                         help="Mapillary API access token. Required unless --skip-lights is set.")
    parser.add_argument("--skip-osm", action="store_true",
                         help="Skip OSM street ingestion (use existing road_segments).")
    parser.add_argument("--skip-lights", action="store_true",
                         help="Skip Mapillary ingestion (use existing streetlights).")
    args = parser.parse_args()

    if not args.skip_lights and (not args.bbox or not args.mapillary_token):
        parser.error("--bbox and --mapillary-token are required unless --skip-lights is set.")

    engine = create_engine(settings.DATABASE_URL)
    Base.metadata.create_all(bind=engine)

    if not args.skip_osm:
        if args.lat is not None and args.lon is not None:
            print(f"Ingesting OSM street network around ({args.lat}, {args.lon}), "
                  f"radius {args.radius}m...")
            ingest_osm(
                db_url=settings.DATABASE_URL,
                center_point=(args.lat, args.lon),
                dist=args.radius,
            )
        else:
            print(f"Ingesting OSM street network for '{args.place}'...")
            ingest_osm(place_name=args.place, db_url=settings.DATABASE_URL)
    else:
        print("Skipping OSM ingestion.")

    if not args.skip_lights:
        print(f"Ingesting Mapillary streetlights for bbox {args.bbox}...")
        ingest_mapillary(bbox=args.bbox, access_token=args.mapillary_token, db_url=settings.DATABASE_URL)
    else:
        print("Skipping Mapillary ingestion.")

    print("Loading roads and lights from PostGIS for scoring...")
    roads_gdf = load_roads(engine)
    lights_gdf = load_lights(engine)
    print(f"  {len(roads_gdf)} road segments, {len(lights_gdf)} streetlights loaded.")

    score_and_write_segments(engine, roads_gdf, lights_gdf)

    # Regenerate the map's surveyed-area outline from the network we just
    # scored, so the two can never describe different areas.
    export_coverage_boundary(roads_gdf)

    print("Pipeline complete.")



if __name__ == "__main__":
    main()